### ISSUE TITLE
import of b2d fails

### ISSUE THREAD

**Issue by pmarcellino** [jtpio/scipy-2022-virtual-poster#5]
I clicked the link on the main page and tried to run the 0_tutorial.ipynb, but get an error in the third cell
![image](https://user-images.githubusercontent.com/46568443/176311194-646e4a1c-559e-4557-a054-c3de80e149f6.png)

**Comment by jtpio** [comment]
Thanks @pmarcellino for reporting.

Yes `pyb2d` does not seem to be installable for now. I opened https://github.com/emscripten-forge/recipes/issues/117 to track this.

**Comment by jtpio** [comment]
Closing as the example notebooks importing `b2d` have been removed.
